//
//  PhotosInteractor.swift
//  RentateamTest
//
//  Created by Виктор Григорьев on 04/09/2019.
//  Copyright (c) 2019 Виктор Григорьев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosBusinessLogic
{
  func doSomething(request: Photos.Something.Request)
}

protocol PhotosDataStore
{
  //var name: String { get set }
}

class PhotosInteractor: PhotosBusinessLogic, PhotosDataStore
{
  var presenter: PhotosPresentationLogic?
  var worker: PhotosWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Photos.Something.Request)
  {
    worker = PhotosWorker()
    worker?.doSomeWork()
    
    let response = Photos.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
