//
//  PhotosDescriptionPresenter.swift
//  RentateamTest
//
//  Created by Виктор Григорьев on 05/09/2019.
//  Copyright (c) 2019 Виктор Григорьев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosDescriptionPresentationLogic
{
  func presentSomething(response: PhotosDescription.Something.Response)
}

class PhotosDescriptionPresenter: PhotosDescriptionPresentationLogic
{
  weak var viewController: PhotosDescriptionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PhotosDescription.Something.Response)
  {
    let viewModel = PhotosDescription.Something.ViewModel()
  }
}
