//
//  PhotosDescriptionViewController.swift
//  RentateamTest
//
//  Created by Виктор Григорьев on 05/09/2019.
//  Copyright (c) 2019 Виктор Григорьев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

class PhotosDescriptionViewController: UIViewController {
    // MARK: Variables
    var photo: Photo?
  
    // MARK: Outlets
    @IBOutlet weak var photoImageView: UIImageView!
    @IBOutlet weak var phNameLabel: UILabel!
    @IBOutlet weak var photoUrlLabel: UILabel!
    @IBOutlet weak var dateOfCaching: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    func setupView() {
        if let photo = self.photo {
            photoImageView.sd_setImage(with: photo.photoUrl, completed: nil)
            phNameLabel.text = photo.phName
            photoUrlLabel.text = photo.phLink
            dateOfCaching.text = photo.date?.getString()
        }
    }
    
}
