//
//  PhotoDescriptionPresenter.swift
//  RentateamTest
//
//  Created by Виктор Григорьев on 05/09/2019.
//  Copyright (c) 2019 Виктор Григорьев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDescriptionPresentationLogic
{
  func presentSomething(response: PhotoDescription.Something.Response)
}

class PhotoDescriptionPresenter: PhotoDescriptionPresentationLogic
{
  weak var viewController: PhotoDescriptionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PhotoDescription.Something.Response)
  {
    let viewModel = PhotoDescription.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
