//
//  PhotosDescriptionViewController.swift
//  RentateamTest
//
//  Created by Виктор Григорьев on 05/09/2019.
//  Copyright (c) 2019 Виктор Григорьев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

protocol PhotosDescriptionDisplayLogic: class
{
  
}

class PhotosDescriptionViewController: UIViewController, PhotosDescriptionDisplayLogic
{
    var interactor: PhotosDescriptionBusinessLogic?
    var router: (NSObjectProtocol & PhotosDescriptionRoutingLogic & PhotosDescriptionDataPassing)?
    var photo: Photo?
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PhotosDescriptionInteractor()
    let presenter = PhotosDescriptionPresenter()
    let router = PhotosDescriptionRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
  
    // MARK: Outlets
    @IBOutlet weak var photoImageView: UIImageView!
    @IBOutlet weak var phNameLabel: UILabel!
    @IBOutlet weak var photoUrlLabel: UILabel!
    @IBOutlet weak var dateOfCaching: UILabel!
    
    func setupView() {
        if let photo = self.photo {
            photoImageView.sd_setImage(with: photo.photoUrl, completed: nil)
            phNameLabel.text = photo.phName
            photoUrlLabel.text = photo.phLink
        }
    }
    
}
