//
//  PhotosDescriptionInteractor.swift
//  RentateamTest
//
//  Created by Виктор Григорьев on 05/09/2019.
//  Copyright (c) 2019 Виктор Григорьев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosDescriptionBusinessLogic
{
  func doSomething(request: PhotosDescription.Something.Request)
}

protocol PhotosDescriptionDataStore
{
  //var name: String { get set }
}

class PhotosDescriptionInteractor: PhotosDescriptionBusinessLogic, PhotosDescriptionDataStore
{
  var presenter: PhotosDescriptionPresentationLogic?
  var worker: PhotosDescriptionWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PhotosDescription.Something.Request)
  {
    worker = PhotosDescriptionWorker()
    worker?.doSomeWork()
    
    let response = PhotosDescription.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
